- id: kvm_install
  type: puppet
  version: 2.0.0
  groups: [compute]
  required_for: [firewall]
  requires: [tools]
  parameters:
    puppet_manifest: puppet/manifests/kvm-install.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 720
